const state={target:6000,filter:'',participants:['Aarav','Beena','Chris','Divya','Eshan','Farah'].map(name=>({name,paid:0}))};
const $=id=>document.getElementById(id);const money=value=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(Math.abs(value||0));const signedMoney=value=>`${value<0?'-':''}${money(value)}`;
const normalizeName=name=>name.trim().replace(/\s+/g,' ').replace(/[.]+$/g,'').toLowerCase().replace(/\b\w/g,char=>char.toUpperCase());
function parseAmount(value){let text=String(value??'').trim();if(!text)return null;text=text.replace(/[₹$€£\s]/g,'').replace(/,/g,'');if(!/^\d+(\.\d{1,2})?$/.test(text))return null;const amount=Number(text);return Number.isFinite(amount)&&amount>=0?Math.round(amount*100)/100:null}
function escapeHtml(value){return String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]))}
function settlements(share){const debtors=state.participants.filter(person=>share-person.paid>.005).map(person=>({name:person.name,amount:share-person.paid}));const creditors=state.participants.filter(person=>person.paid-share>.005).map(person=>({name:person.name,amount:person.paid-share}));const result=[];let debtorIndex=0,creditorIndex=0;while(debtorIndex<debtors.length&&creditorIndex<creditors.length){const debtor=debtors[debtorIndex],creditor=creditors[creditorIndex],amount=Math.min(debtor.amount,creditor.amount);result.push({from:debtor.name,to:creditor.name,amount});debtor.amount-=amount;creditor.amount-=amount;if(debtor.amount<.005)debtorIndex++;if(creditor.amount<.005)creditorIndex++}return result}
function render(){const share=state.participants.length?state.target/state.participants.length:0;const collected=state.participants.reduce((sum,person)=>sum+person.paid,0);const remaining=Math.max(0,state.target-collected);const progress=state.target?Math.min(100,collected/state.target*100):0;$('heroShare').textContent=money(share);$('shareAmount').textContent=money(share);$('totalCollected').textContent=money(collected);$('remainingAmount').textContent=money(remaining);$('collectionCaption').textContent=`of ${money(state.target)} target`;$('remainingCaption').textContent=remaining?`${money(remaining)} left before target`:'Target collected';$('participantCount').textContent=`${state.participants.length} ${state.participants.length===1?'person':'people'}`;$('progressBar').style.width=`${progress}%`;$('tableTotal').textContent=`Total ${money(collected)}`;$('poolStatus').textContent=!state.participants.length?'Needs people':remaining?'Collecting':'Fully collected';$('statusCaption').textContent=remaining?`${Math.round(progress)}% of target`:'Ready to settle';$('headerStatus').textContent=remaining?'Pool in progress':'Pool fully collected';
$('participantsBody').innerHTML=state.participants.map((person,index)=>({person,index})).filter(({person})=>person.name.toLowerCase().includes(state.filter)).map(({person,index})=>{const balance=person.paid-share,status=balance<-.005?'Owes':balance>.005?'Gets back':'Settled',kind=balance<-.005?'owe':balance>.005?'get':'even';return `<tr><td class="person-cell">${escapeHtml(person.name)}</td><td class="mono">${money(share)}</td><td><input class="amount-input" data-index="${index}" type="number" min="0" step="0.01" value="${person.paid||''}" aria-label="Amount paid by ${escapeHtml(person.name)}"></td><td class="mono balance-${kind}">${balance<-.005?signedMoney(balance):balance>.005?`+${money(balance)}`:money(0)}</td><td><span class="pill ${kind}">${status}</span></td></tr>`}).join('')||'<tr><td colspan="5" class="muted">No matching participant.</td></tr>';
document.querySelectorAll('.amount-input').forEach(input=>input.addEventListener('change',event=>{state.participants[Number(event.target.dataset.index)].paid=parseAmount(event.target.value)||0;render()}));const transfers=settlements(share);$('settlementMessage').style.display=transfers.length?'none':'flex';$('settlementList').innerHTML=transfers.map(item=>`<article class="settlement-card"><div class="transfer">${escapeHtml(item.from)}<span>→</span>${escapeHtml(item.to)}</div><strong>${money(item.amount)}</strong></article>`).join('')}
function importContributions(){const raw=$('importText').value.trim();if(!raw){window.alert('Paste contribution rows or choose a file first.');return}const lines=raw.split(/\r?\n/).map(line=>line.trim()).filter(Boolean),accepted=[],rejected=[],merged=new Set(),seen=new Set();let duplicates=0;lines.forEach((line,index)=>{if(index===0&&/name/i.test(line)&&/amount|paid|contribution/i.test(line))return;const parts=line.split(/[,;\t|]/).map(value=>value.trim());if(parts.length<2){rejected.push({line:index+1,reason:'Expected a name and amount'});return}const name=normalizeName(parts[0]),amount=parseAmount(parts.slice(1).join(' '));if(!name||name.length<2){rejected.push({line:index+1,reason:'Missing or invalid name'});return}if(amount===null){rejected.push({line:index+1,reason:'Invalid amount format'});return}const key=`${name.toLowerCase()}|${amount}`;if(seen.has(key)){duplicates++;return}seen.add(key);accepted.push({name,amount})});const totals=new Map();accepted.forEach(item=>{const key=item.name.toLowerCase();if(totals.has(key))merged.add(item.name);totals.set(key,(totals.get(key)||0)+item.amount)});const known=new Map(state.participants.map(person=>[person.name.toLowerCase(),person])),unknown=[];totals.forEach((amount,key)=>{if(known.has(key))known.get(key).paid=amount;else unknown.push(key)});state.participants=state.participants.map(person=>({...person,paid:known.get(person.name.toLowerCase())?.paid||0}));render();const invalid=rejected.length;const report=$('importReport');report.hidden=false;report.innerHTML=`<div class="report-grid"><div class="report-stat"><strong>${accepted.length}</strong><span>rows accepted</span></div><div class="report-stat"><strong>${duplicates}</strong><span>duplicates removed</span></div><div class="report-stat"><strong>${merged.size}</strong><span>names merged</span></div><div class="report-stat"><strong>${invalid}</strong><span>rows rejected</span></div></div><p class="report-note"><strong>Cleaned total:</strong> ${money([...totals.values()].reduce((sum,value)=>sum+value,0))} across ${totals.size} normalized names.</p>${unknown.length?`<p class="report-note"><strong>Not in pool:</strong> ${unknown.join(', ')}.</p>`:''}<p class="report-note"><strong>De-duplicated:</strong> ${duplicates} exact duplicate row${duplicates===1?'':'s'} removed before totals were calculated.</p><p class="report-note"><strong>Rejected:</strong> ${invalid?rejected.map(item=>`row ${item.line}: ${escapeHtml(item.reason)}`).join(' · '):'No invalid rows.'}</p>`}
$('applyPool').addEventListener('click',()=>{const target=parseAmount($('targetAmount').value),names=[...new Set($('participantNames').value.split(',').map(normalizeName).filter(Boolean))];if(!target||!names.length){window.alert('Enter a target amount and at least one participant.');return}const old=new Map(state.participants.map(person=>[person.name.toLowerCase(),person.paid]));state.target=target;state.participants=names.map(name=>({name,paid:old.get(name.toLowerCase())||0}));$('rowHint').textContent=`${names.length} participants · enter or import payments below`;render()});$('resetData').addEventListener('click',()=>{state.participants.forEach(person=>person.paid=0);render()});$('loadSample').addEventListener('click',()=>{$('importText').value=`Name, Amount\nAarav, ₹1,500\nBeena, 750\nChris, 1,000\nChris, ₹250\nDivya, 1500\nDivya, 1,500\nEshan, 0\nFarah, 2,000\nfarah., ₹2,000\nBad row, twelve hundred\n, ₹300`});$('importButton').addEventListener('click',importContributions);$('fileInput').addEventListener('change',event=>{const file=event.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{$('importText').value=reader.result};reader.readAsText(file)});render();

const storageKey='common-ground-pool-v1';
const savedPool=window.localStorage.getItem(storageKey);
if(savedPool){try{const recovered=JSON.parse(savedPool);if(Number.isFinite(recovered.target)&&Array.isArray(recovered.participants)){state.target=recovered.target;state.participants=recovered.participants.filter(person=>person&&person.name).map(person=>({name:normalizeName(person.name),paid:parseAmount(person.paid)||0}));$('targetAmount').value=state.target;$('participantNames').value=state.participants.map(person=>person.name).join(', ');render()}}catch(error){window.localStorage.removeItem(storageKey)}}

function persistPool(){window.localStorage.setItem(storageKey,JSON.stringify({target:state.target,participants:state.participants,savedAt:new Date().toISOString()}))}
function downloadFile(filename,content,type){const link=document.createElement('a');link.href=URL.createObjectURL(new Blob([content],{type}));link.download=filename;document.body.appendChild(link);link.click();link.remove();window.setTimeout(()=>URL.revokeObjectURL(link.href),1000)}
function csvCell(value){return `"${String(value).replace(/"/g,'""')}"`}
function exportContributions(){downloadFile('common-ground-contributions.csv',participantCsvRows().map(row=>row.map(csvCell).join(',')).join('\n'),'text/csv;charset=utf-8')}
function exportBackup(){downloadFile('common-ground-backup.json',exportSummaryJson(),'application/json')}
function settlementText(){const share=state.participants.length?state.target/state.participants.length:0;const transfers=settlements(share);return transfers.length?transfers.map(item=>`${item.from} pays ${item.to} ${money(item.amount)}`).join('\n'):'Everyone is settled. No transfers needed.'}
function copySettlement(){navigator.clipboard?.writeText(settlementText()).then(()=>showToast('Settlement copied')).catch(()=>window.alert(settlementText()))}
function showToast(message){const toast=document.createElement('div');toast.className='app-toast';toast.textContent=message;document.body.appendChild(toast);window.setTimeout(()=>toast.remove(),2200)}
function rememberAfterRender(){persistPool();}
const originalRender=render;
render=function(){originalRender();rememberAfterRender()};
$('exportCsv').addEventListener('click',exportContributions);$('exportJson').addEventListener('click',exportBackup);$('copySettlement').addEventListener('click',copySettlement);
$('applyPool').addEventListener('click',()=>{window.setTimeout(()=>{persistPool();showToast('Pool updated')},0)});$('resetData').addEventListener('click',()=>showToast('Amounts reset'));
$('importText').addEventListener('dragover',event=>{event.preventDefault();event.currentTarget.classList.add('drop-ready')});$('importText').addEventListener('dragleave',event=>event.currentTarget.classList.remove('drop-ready'));$('importText').addEventListener('drop',event=>{event.preventDefault();event.currentTarget.classList.remove('drop-ready');const file=event.dataTransfer.files[0];if(file){const reader=new FileReader();reader.onload=()=>{event.currentTarget.value=reader.result;$('importText').dispatchEvent(new Event('input'))};reader.readAsText(file)}});
function auditText(){const report=$('importReport');return report&&!report.hidden?`${auditLines().join('\n')}\n\nImport details:\n${report.innerText}`:auditLines().join('\n')}
function downloadAudit(){downloadFile('common-ground-audit.txt',auditText(),'text/plain;charset=utf-8');showToast('Audit downloaded')}
function restoreBackup(){const file=$('fileInput').files[0];if(!file){showToast('Choose a JSON backup first');return}const reader=new FileReader();reader.onload=()=>{try{loadBackupObject(JSON.parse(reader.result));showToast('Backup restored')}catch(error){window.alert('This is not a valid Common Ground backup file.')}};reader.readAsText(file)}
function printReport(){window.print()}
$('participantSearch').addEventListener('input',event=>{state.filter=event.target.value.trim().toLowerCase();render()});$('printReport').addEventListener('click',printReport);$('restoreJson').addEventListener('click',restoreBackup);
document.addEventListener('keydown',event=>{if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='s'){event.preventDefault();exportBackup();showToast('Backup downloaded')}if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='p'){event.preventDefault();printReport()}if(event.key==='Escape'&&document.activeElement?.tagName==='TEXTAREA'){document.activeElement.blur()}});

function toCents(value){return Math.round((Number(value)||0)*100)}
function fromCents(value){return value/100}
function sumCents(values){return values.reduce((total,value)=>total+toCents(value),0)}
function currentShare(){return state.participants.length?state.target/state.participants.length:0}
function balanceFor(person,share=currentShare()){return person.paid-share}
function statusForBalance(balance){if(balance<-.005)return {label:'Owes',className:'owe'};if(balance>.005)return {label:'Gets back',className:'get'};return {label:'Settled',className:'even'}}
function participantSnapshot(){const share=currentShare();return state.participants.map(person=>{const balance=balanceFor(person,share);const status=statusForBalance(balance);return{name:person.name,paid:person.paid,share,balance,status:status.label}})}
function collectionSummary(){const rows=participantSnapshot();const collected=fromCents(sumCents(rows.map(row=>row.paid)));const target=fromCents(toCents(state.target));const outstanding=Math.max(0,target-collected);const overage=Math.max(0,collected-target);return{target,collected,outstanding,overage,progress:target?Math.min(100,collected/target*100):0,participants:rows.length,settled:rows.filter(row=>row.status==='Settled').length,owing:rows.filter(row=>row.status==='Owes').length,receiving:rows.filter(row=>row.status==='Gets back').length}}
function settlementSummary(){const summary=collectionSummary();const transfers=settlements(currentShare());const transferTotal=fromCents(sumCents(transfers.map(item=>item.amount)));return{transfers,total:transferTotal,count:transfers.length,complete:summary.owing===0||summary.receiving===0}}
function auditLines(){const summary=collectionSummary();const settlement=settlementSummary();return[`Pool: ${$('poolName').value||'Shared gift pool'}`,`Target: ${money(summary.target)}`,`Collected: ${money(summary.collected)}`,`Outstanding: ${money(summary.outstanding)}`,`Overage: ${money(summary.overage)}`,`Participants: ${summary.participants}`,`Settled: ${summary.settled}`,`Owing: ${summary.owing}`,`Receiving: ${summary.receiving}`,`Settlement transfers: ${settlement.count}`,`Settlement total: ${money(settlement.total)}`,`Generated: ${new Date().toLocaleString('en-IN')}`]}
function participantCsvRows(){return[['Participant','Fair share','Paid','Balance','Status'],...participantSnapshot().map(row=>[row.name,row.share,row.paid,row.balance,row.status])]}
function exportSummaryJson(){const summary=collectionSummary();return JSON.stringify({poolName:$('poolName').value||'Shared gift pool',summary,participants:participantSnapshot(),settlement:settlementSummary(),exportedAt:new Date().toISOString()},null,2)}
function validatePoolDraft(){const target=parseAmount($('targetAmount').value);const names=$('participantNames').value.split(',').map(normalizeName).filter(Boolean);const duplicateCount=names.length-new Set(names.map(name=>name.toLowerCase())).size;return{valid:Boolean(target&&names.length),target,names,duplicateCount,errors:[!target?'Target must be a positive amount.':'',!names.length?'Add at least one participant.':''].filter(Boolean)}}
function announcePoolValidation(){const validation=validatePoolDraft();if(validation.duplicateCount>0)showToast(`${validation.duplicateCount} duplicate participant name${validation.duplicateCount===1?'':'s'} will be merged`);return validation}
function safeFilename(value){return String(value||'common-ground').trim().toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'')||'common-ground'}
function exportNamedFile(extension,content,type){downloadFile(`${safeFilename($('poolName').value)}-${extension}`,content,type)}
function downloadDetailedAudit(){const lines=[...auditLines(),'','Participants:',...participantSnapshot().map(row=>`${row.name}: paid ${money(row.paid)}, balance ${signedMoney(row.balance)}, ${row.status}`),'','Transfers:',...settlementSummary().transfers.map(item=>`${item.from} pays ${item.to} ${money(item.amount)}`)];exportNamedFile('audit.txt',lines.join('\n'),'text/plain;charset=utf-8')}
function loadBackupObject(backup){if(!backup||!Array.isArray(backup.participants)||!Number.isFinite(Number(backup.target)))throw new Error('Invalid backup shape');const people=backup.participants.map(person=>({name:normalizeName(person.name),paid:parseAmount(person.paid)||0})).filter(person=>person.name);if(!people.length)throw new Error('Backup has no participants');state.target=parseAmount(backup.target);state.participants=people;$('targetAmount').value=state.target;$('participantNames').value=people.map(person=>person.name).join(', ');render();persistPool()}
function resetImportReport(){const report=$('importReport');report.hidden=true;report.innerHTML=''}
function clearSearch(){state.filter='';$('participantSearch').value='';render()}
function updateActionLabels(){const summary=collectionSummary();$('rowHint').textContent=`${summary.participants} participants · ${summary.settled} settled · ${summary.owing} owing · ${summary.receiving} receiving`}
$('applyPool').addEventListener('click',()=>{announcePoolValidation();window.setTimeout(updateActionLabels,0)});
$('downloadAudit').addEventListener('click',downloadDetailedAudit);
$('participantSearch').addEventListener('search',clearSearch);
